LucasAnimalFacts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import settings

from pages.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='page_home'),
    path('animals/', include('animals.urls')),
    path('travel/', include('travel.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animals/urls.py
from django.urls import path

from animals.views import AnimalDetailView, AnimalListView, AnimalSearch

app_name = 'animals'
urlpatterns = [
    path('<slug:slug>/', AnimalDetailView.as_view(), name='animal_detail'),
    path('', AnimalListView.as_view(), name='animal_list'),
    path('search_results', AnimalSearch, name='search')
]

travel/urls.py
from django.urls import path

from travel.views import TravelListView, TravelDetailView

app_name = 'travel'
urlpatterns = [
    path('<slug:slug>/', TravelDetailView.as_view(), name='travel_detail'),
    path('', TravelListView.as_view(), name='travel_list'),
]

templates/Animal_Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/navstyle.css' %}">
    <link rel="stylesheet" href="{% static 'styles/animalstyles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/animal_list.css' %}">
    <link rel="stylesheet" href="{% static 'styles/results.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
        replace me
    {% endblock %}

    {% include 'footer.html' %}

    <script src="{% static 'scripts/carousel.js' %}"></script>
</body>
</html>

templates/animal_detail.html
{% extends 'Animal_Base.html' %}
{% load static %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="header">
        <h1>{{ object.name }}</h1>
        <img src="{{ object.image.all.first.image.url }}" alt="object.image.all.first.description">
        <p>Written by {{ object.writer }}</p>
        <p>{{ object.date }}</p>
    </div>

    <div class="table-sect">
        <div class="desktop-table">
            <table>
                <tr>
                    <td>Common Name: {{ object.common_name }}</td>
                    <td>Scientific Name: {{ object.scientific_name }}</td>
                    <td>Type: {{ object.animal_class }}</td>
                </tr>
                <tr>
                    <td>Diet: {{ object.diet }}</td>
                    <td>Average Life Span In The Wild: {{ object.avg_life_span }}</td>
                    <td>Weight: {{ object.weight }}</td>
                </tr>
                <tr>
                    <td class="bottom-row">Size: {{ object.size }}</td>
                    <td class="bottom-row">Habitat: {{ object.habitat }}</td>
                    <td class="bottom-row">Current Population Trend: {{ object.cur_pop_trend }}</td>
                </tr>
                </div>
            </table>
        </div>

        <div class="mobile-table">

        </div>
    </div>

    <div class="animal-info-sect">
        {% for portion in split_info %}
            <p>{{ portion }}</p>
        {% endfor %}
    </div>

    <div class="carousel">
        <button class="carousel-button carousel-button-left">
            <img src="{% static 'mainpictures/key-left-svgrepo-com.svg' %}"  alt="">
        </button>
        <div class="carousel-track-container">
            <ul class="carousel-track">
                <li class="carousel-slide current-slide">
                    <img class="carousel-image" src="{{ object.image.all.first.image.url }}" alt="{{ object.image.all.first.description }}">
                </li>
                <li class="carousel-slide">
                    <img class="carousel-image" src="{{ object.image.all.1.image.url }}" alt="{{ object.image.all.1.description }}">
                </li>
                <li class="carousel-slide">
                    <img class="carousel-image" src="{{ object.image.all.last.image.url }}" alt="{{ object.image.all.last.description }}">
                </li>
            </ul>
        </div>
        <button class="carousel-button carousel-button-right">
            <img src="{% static '/mainpictures/key-left-svgrepo.com.svg' %}"  alt="">
        </button>

        <div class="carousel-nav">
            <button class="carousel-indicator current-slide"></button>
            <button class="carousel-indicator"></button>
            <button class="carousel-indicator"></button>
        </div>
    </div>
{% endblock %}

templates/animal_list.html
{% extends 'Animal_Base.html' %}
{% load static %}
{% block title %}All animals{% endblock %}
{% block content %}

    <span class="header-text"><h1>All Animals</h1></span>
    <span class="alphabet-container"><p><a href="#a">a</a> <a href="#b">b</a> <a href="#c">c</a> <a href="#d">d</a> <a href="#e">e</a> <a href="#f">f</a> <a href="#g">g</a> <a href="#h">h</a> <a href="#i">i</a> <a href="#j">j</a> <a href="#k">k</a> <a href="#l">l</a> <a href="#m">m</a> <a href="#n">n</a> <a href="#o">o</a> <a href="#p">p</a> <a href="#q">q</a> <a href="#r">r</a> <a href="#s">s</a> <a href="#t">t</a> <a href="#u">u</a> <a href="#v">v</a> <a href="#w">w</a> <a href="#x">x</a> <a href="#y">y</a> <a href="#z">z</a> </p></span>

    <div class="list-container">

        <h1 id="a">A</h1>
        <br>
        <div class="grid-container">
            {% for animal in obj.0 %}
                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>


        <h1 id="b">B</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.1 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="c">C</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.2 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="d">D</h1>
        <br>
        
        <div class="grid-container">
            {% for animal in obj.3 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="e">E</h1>

        <br>
        <div class="grid-container">
        {% for animal in obj.4 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>

        <h1 id="f">F</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.5 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        
        <h1 id="g">G</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.6 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="h">H</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.7 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="i">I</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.8 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="j">J</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.9 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="k">K</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.10 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="l">L</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.11 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="m">M</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.12 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="n">N</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.13 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="o">O</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.14 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="p">P</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.15 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="q">Q</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.16 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="r">R</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.17 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="s">S</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.18 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="t">T</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.19 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="u">U</h1>

        <br>
        <div class="grid-container"> 
            {% for animal in obj.20 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="v">V</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.21 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="w">W</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.22 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="x">X</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.23 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="y">Y</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.24 %}

                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <h1 id="z">Z</h1>

        <br>
        <div class="grid-container">
            {% for animal in obj.25 %}
                <a href="{{ animal.get_absolute_url }}">
                    <div class="animal-container">
                        <img src="{{ animal.image.all.first.image.url }}" alt="{{ animal.image.all.first.description }}">
                        <p>{{ animal.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/styles/navstyle.css">
    <link rel="stylesheet" href="static/styles/homestyles.css">
    <link rel="stylesheet" href="static/styles/footer.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
        replace me
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="footer-wrapper">
    <h1 class="footer-title-left">Lucas Animal Facts</h1>
    <ul class="footer-list-pages">
        <li class="footage-list-item">Animals</li>
        <li class="footage-list-item">Travel</li>
        <li class="footage-list-item">News</li>
        <li class="footage-list-item">Contact</li>
    </ul>
    <h1 class="footer-title-right">Follow Me</h1>
    <ul class="footer-list-follow">
        <li class="footage-list-item"><a href="www.instagram.com">Instagram</a></li>
        <li class="footage-list-item"><a href="www.twitter.com">Twitter</a></li>
        <li class="footage-list-item"><a href="www.facebook.com">Facebook</a></li>
    </ul>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %}LucasAnimalFacts{% endblock %}

{% block content %}
<div class="hero-main">
    <h1 class="main-title">Featured</h1>
    <div class="hero-sect">
        <div class="img-sect">
            <a href="{{ animal_obj.get_absolute_url }}">
                <img src="{{ animal_obj.image.all.first.image.url }}" alt="">
            </a>
            <div class="img-info">
                <h1>Featured Animal - {{ animal_obj.name }}</h1>
            </div>
        </div>
        <div class="cta">
            <div class="cta-container">
                <h1>Discover many more animals!</h1>
                <a href="{% url 'animals:animal_list' %}">Discover</a>
            </div>
        </div>
    </div>
</div>

    <div class="travel">
        <h1>Travel</h1>
        <ul class="travel-list">
            {% for i in travel_list %}
            <li>
                <a href="{{ i.get_absolute_url }}">
                    <div class="travel-item">
                        <img src="{{ i.image.all.first.image.url }}" alt="{{ i.image.all.first.description }}">
                        <h1>Travel - {{ i.title }}</h1>
                        <p>{{ i.short_description }}</p>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="news">
        <h1>News</h1>
        <ul class="news-sect">
            {% for i in news_list %}
            <li class="news-item">
                <img src="{{ i.image.all.first.image.url }}" alt="{{ i.image.all.first.description }}">
                <p>{{ i.short_description }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/navbar.html
{% load static %}
<div class="navbar">
    <div class="container">
        <div class="main-element">
            <a href="{% url 'page_home' %}">
                <img class="mainlogo" src="{% static '/mainpictures/Animal Facts Bannertansparences.png' %}" alt="">
            </a>
            <img id="menu-btn" class="menu-btn" src="{% static '/mainpictures/menu.svg' %}" alt="">
        </div>
        <nav>
            <img id="exit-btn" class="exit-btn" src="{% static '/mainpictures/exit.svg' %}" alt="">
            <ul class="nav-element"> 
                <a href="{% url 'animals:animal_list' %}"><li>Animals</li></a>
                <a href=""><li>News</li></a>
                <a href="{% url 'travel:travel_list' %}"><li>Travel</li></a>
                <li><form method="POST" action="{% url 'animals:search' %}">
                    {% csrf_token %}
                    <input class="search" type="search" placeholder="Search" name="searched">
                    <button type="submit">Search</button>
                </form></li>
            </ul>
        </nav>
        
    </div>
</div>

<script src="{% static '/scripts/index.js' %}"></script>

templates/search_results.html
{% extends 'Animal_Base.html' %}
{% load static %}
{% block title %}Results{% endblock %}
{% block content %}
        {% if searched %}
            <h1 class="search-term">You Searched For {{searched}}</h1>
            <br/>
            <div class="results-area">
                {% for result in animals %}
                <div class="individual-result">
                    <a href="{{ result.get_absolute_url }}">
                        <img src="{{ result.image.all.first.image.url }}" alt="">
                        <h1>{{ result.name }}</h1>
                    </a>
                </div>
                <br/>
                {% endfor %}
            </div>
        {% endif %}
{% endblock %}

templates/travel_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/navstyle.css' %}">
    <link rel="stylesheet" href="{% static 'styles/animalstyles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/animal_list.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
        replace me
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/travel_detail.html
{% extends 'travel_base.html' %}
{% load static %}
{% block title %}Travel - {{ object.title }}{% endblock %}
{% block content %}

    <div class="header">
        <h1>{{ object.name }}</h1>
        <img src="{{ object.image.all.first.image.url }}" alt="object.image.all.first.description">
        <p>Written by {{ object.writer }}</p>
        <p>{{ object.date }}</p>
    </div>

        <div class="animal-info-sect">
            {% for portion in split_info %}
            <p>{{ portion }}</p>
            {% endfor %}
        </div>
        
        <div class="carousel">
            <button class="carousel-button carousel-button-left">
                <img src="{% static 'mainpictures/key-left-svgrepo-com.svg' %}" alt="">
            </button>
            <div class="carousel-track-container">
                <ul class="carousel-track">
                    <li class="carousel-slide current-slide">
                        <img class="carousel-image" src="{{ object.image.all.first.image.url }}"
                            alt="{{ object.image.all.first.description }}">
                    </li>
                    <li class="carousel-slide">
                        <img class="carousel-image" src="{{ object.image.all.1.image.url }}"
                            alt="{{ object.image.all.1.description }}">
                    </li>
                    <li class="carousel-slide">
                        <img class="carousel-image" src="{{ object.image.all.last.image.url }}"
                            alt="{{ object.image.all.last.description }}">
                    </li>
                </ul>
            </div>
            <button class="carousel-button carousel-button-right">
                <img src="{% static '/mainpictures/key-left-svgrepo.com.svg' %}" alt="">
            </button>
        
            <div class="carousel-nav">
                <button class="carousel-indicator current-slide"></button>
                <button class="carousel-indicator"></button>
                <button class="carousel-indicator"></button>
            </div>
        </div>



{% endblock %}